version: '3'

services:
  db:
    container_name: platform_database
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./backend/.env
    networks:
      - platform_net
  backend:
    build: backend
    user: node
    container_name: platform_backend
    tty: true
    stdin_open: true
    command: start:dev
    restart: always
    working_dir: /backend
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    networks:
      - platform_net
  frontend:
    build: frontend
    user: node
    container_name: platform_frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - platform_net

networks:
  platform_net:
    driver: bridge